# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96cbbabb9e330c0cfac1d52212efba0a6e3623801d757c3f508de9ad5dd232d0b215571fe184dca04cfe3019224016538a306e6e28358d990bbe575bcd67f2b5

test:
  secret_key_base: e187d313becb999d12f57de83b83217b66e02255bb4f5133c55ee29dab112afc6c82dcf28069a874c732e47c6bc855df0e6d10ecc0479ac98891d682d13964a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
